version: "3.8"
services:
  frontend:
    build: ./frontend
    container_name: app_frontend
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
  backend:
    build: ./backend
    container_name: app_backend
    environment:
      NODE_ENV: production
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      REDIS_HOST: 127.0.0.1
      REDIS_PORT: 6379
      REDIS_PASSWORD: password
      CHOKIDAR_USEPOLLING: true
    ports:
      - 3001:3001
    links:
      - "redis:app_sessions"
      - "postgres:app_postgres"
    volumes:
      - ./backend:/app
    command: yarn prod
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass password
    environment:
      - REDIS_PASSWORD=password
    volumes:
      - app_sessions:/data/
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - app_postgres:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - "5432:5432"
volumes:
  app_sessions:
    driver: local
  app_postgres:
    driver: local
